# Generated by Django 4.1.7 on 2023-03-17 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("email", models.CharField(max_length=30)),
                ("phone_number", models.CharField(max_length=30)),
                ("company", models.CharField(max_length=30)),
                ("message", models.CharField(max_length=30)),
            ],
        ),
    ]
