# Generated by Django 4.1.7 on 2023-03-23 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_newsletter"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description1", models.TextField(max_length=300)),
                ("description2", models.TextField(max_length=250)),
                ("image", models.ImageField(upload_to="")),
            ],
        ),
    ]
