# Generated by Django 4.1.7 on 2023-03-23 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_productmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="productmodel",
            name="category",
            field=models.CharField(default="default_category", max_length=100),
        ),
    ]
