# Generated by Django 4.1.7 on 2023-03-23 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_productmodel_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="productmodel",
            name="link",
            field=models.URLField(default="", max_length=150),
        ),
    ]
