# Generated by Django 4.1.7 on 2023-03-23 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_productmodel_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="productmodel",
            name="characteristic",
            field=models.CharField(default="", max_length=150),
        ),
    ]
