# Generated by Django 4.1.7 on 2023-03-27 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_productmodel_characteristic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productmodel",
            name="category",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="productmodel",
            name="description2",
            field=models.TextField(max_length=8400),
        ),
        migrations.AlterField(
            model_name="productmodel",
            name="image",
            field=models.ImageField(upload_to="static/photos"),
        ),
        migrations.AlterField(
            model_name="productmodel",
            name="link",
            field=models.URLField(default="", max_length=300),
        ),
    ]
